spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://:3307/learn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
