spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3307/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
#  security:
#    oauth2:
#      client:
#        registration:
#          gitee:
#            client-id: "feb31e7e0e84faf41a038ca503a44c744fac0b169e48e5a5defb680eab58ac64"
#            client-secret: "ee89f74e0f51f079095b9483b4e536be0f726a5709e3d67ca8cca7e367557dc8"
#            redirect-uri: "http://localhost:8080/oauth/notify"
#            authorization-grant-type: authorization_code
#            scope: user_info
#        provider:
#          gitee:
#            authorization-uri: https://gitee.com/oauth/authorize
#            token-uri: https://gitee.com/oauth/token
#            user-info-uri: https://gitee.com/api/v5/user
#            user-name-attribute: name
#            jwk-set-uri: https://gitee.com/oauth/token/jwk
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: STATUS # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 10001001 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 10001002 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
jwt:
  expiration: 30 #minute
  tokenHead: "Bearer "